### ISSUE TITLE
.spells recipe ? 

### ISSUE THREAD

**Issue by hugsi** [le-phare/flex-recipes#22]
a la génération d'un projet faros par le skeleton, aucun fichier .spells n'est généré

**Comment by lucasmirloup** [comment]
### Proposition : Centraliser tous les scripts / commandes (`composer`, `npm`, `yarn`, `php-cs-fixer`, etc.) à un seul endroit

Je vois au minimum 5 endroits où nous dupliquons nos commandes actuellement :
- Dans les `Makefile`
- Dans les `.spells`
- Dans les `composer.json` / `package.json`
- Dans les hooks de pre-commit Git (rare, mais cela serait une bonne chose de le généraliser)
- Dans les CI : peut-être le seul cas où faire une configuration à part se justifie. Les GitHub Actions sont généralement plus spécialisées et plus adaptées aux CI (mise en cache, mise en forme de l'output, MAJ automatique, etc.)

Les `.spells`, les `composer.json` / `package.json`, les hooks de pre-commit et les scripts de CI ne fonctionnent pas sur toutes les plateformes, ne gèrent pas tous les langages, ou ne permettent pas une réutilisation / surcharge suffisante.

`Makefile` est à mon avis une des solutions répondant au mieux à ces problèmes : il est bien supporté, peu complexe à installer, relativement simple à surcharger, n'est pas limité à un langage en particulier, et peut être appelé depuis les autres contextes dont nous avons besoin (`.spells`, pre-commit, CI, etc.), Docker compris.

### TODO

- [ ] Déplacer toute la logique dans les `Makefile` / `Makefile.mk`
- [ ] Chaque fonction `.spells` appelle une règle Make, ce qui évite les copier-coller entre `Makefile` et `.spells`
- [ ] Dans un second temps, faire de même pour les hooks de pre-commit ou autres contextes

Exemple de `Makefile` / `Makefile.mk` (vite fait) :
```Makefile
docker_run ?= docker run ...
php_version ?= 8.2
COMPOSER_ARGS ?= -v

composer:
	$(docker_run) lephare/php:$(php_version) $(COMPOSER_ARGS)
```

Exemple de `.spells` :
```shell
#!/bin/sh

composer() {
    COMPOSER_ARGS="$@" make composer
}
```

Cc @thislg

**Comment by thislg** [comment]
Makefile n'est pas fait ni adapté aux commandes interactives comme `sf`. Je comprends la problématique mais la proposition est alambiquée.

**Comment by lucasmirloup** [comment]
Comme discuté avec @thislg : avec du recul ça serait assez compliqué de maintenir des `Makefile` et cie., donc pour corriger le pb, j'ai mis un `.spells` en PR.
